version: '3'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - './mongodb/database:/data/db'
    ports:
      - 27017:27017
    restart: "unless-stopped"